# -*- coding: utf-8 -*-
"""evaluate.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p2A_K8mQsk45_gJitaRucUqJJvYCQXdK
"""

#!/usr/bin/env python3
"""
Evaluate a trained YOLOv8‑seg model on the CarDD test set.
Usage:
    python evaluate.py --model path/to/best.pt --data path/to/car_damage.yaml [--split test] [--plots] [--image test.jpg]
"""

import argparse
import os
import sys
import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO

# ------------------------------
# 1. Parse command line arguments
# ------------------------------
parser = argparse.ArgumentParser(description="Evaluate YOLOv8‑seg on CarDD dataset")
parser.add_argument("--model", type=str, required=True,
                    help="Path to the trained model (.pt file).")
parser.add_argument("--data", type=str, required=True,
                    help="Path to the dataset YAML file (e.g., car_damage.yaml).")
parser.add_argument("--split", type=str, default="test",
                    help="Dataset split to evaluate on (default: test).")
parser.add_argument("--plots", action="store_true",
                    help="Generate and save evaluation plots (confusion matrix, PR curves).")
parser.add_argument("--image", type=str, default=None,
                    help="Optional: path to a single image for inference demonstration.")
parser.add_argument("--save_dir", type=str, default=None,
                    help="Directory to save output plots and images. If not provided, they are saved in the model's directory.")
args = parser.parse_args()

# ------------------------------
# 2. Helper: print metrics
# ------------------------------
def print_metrics(metrics, class_names):
    """Print per‑class and overall metrics."""
    print("\n📊 Per‑class mAP50 (box):")
    for i, ap in enumerate(metrics.box.ap):
        print(f"  {class_names[i]}: {ap:.4f}")

    print("\n📊 Per‑class mAP50 (mask):")
    for i, ap in enumerate(metrics.seg.ap):
        print(f"  {class_names[i]}: {ap:.4f}")

    print(f"\n📈 Overall box mAP50: {metrics.box.map50:.4f}")
    print(f"📈 Overall box mAP50-95: {metrics.box.map:.4f}")
    print(f"📈 Overall mask mAP50: {metrics.seg.map50:.4f}")
    print(f"📈 Overall mask mAP50-95: {metrics.seg.map:.4f}")

# ------------------------------
# 3. Main evaluation routine
# ------------------------------
def main():
    # Check if the model file exists
    if not os.path.exists(args.model):
        print(f"ERROR: Model file not found: {args.model}")
        sys.exit(1)
    if not os.path.exists(args.data):
        print(f"ERROR: Dataset YAML not found: {args.data}")
        sys.exit(1)

    # Load the trained model
    print(f"Loading model from {args.model}...")
    model = YOLO(args.model)
    class_names = list(model.names.values())
    print(f"Model class names: {class_names}")

    # Run validation
    print(f"\nEvaluating on {args.split} split...")
    metrics = model.val(data=args.data, split=args.split, plots=args.plots)

    # Print metrics
    print_metrics(metrics, class_names)

    # Save plots if requested
    if args.plots:
        # The plots are already saved in the default runs directory.
        # We can optionally copy them to a custom location.
        if args.save_dir:
            import shutil
            import glob
            # The plots are saved in runs/segment/val (or a timestamped folder)
            # We need to find the most recent validation run directory
            val_runs = glob.glob("runs/segment/val*")
            if val_runs:
                latest = max(val_runs, key=os.path.getctime)
                os.makedirs(args.save_dir, exist_ok=True)
                for file in os.listdir(latest):
                    if file.endswith(('.png', '.pdf', '.jpg')):
                        shutil.copy2(os.path.join(latest, file), args.save_dir)
                print(f"Plots saved to {args.save_dir}")

    # Optionally run inference on a single image
    if args.image:
        if not os.path.exists(args.image):
            print(f"Warning: Image file not found: {args.image}")
        else:
            print(f"\nRunning inference on {args.image}...")
            results = model(args.image)
            annotated = results[0].plot()

            # Display the result (if running in a graphical environment)
            try:
                plt.figure(figsize=(12, 8))
                plt.imshow(cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB))
                plt.axis('off')
                plt.title('Predicted Damages')
                plt.show()
            except Exception:
                pass

            # Save the annotated image if save_dir is provided
            if args.save_dir:
                os.makedirs(args.save_dir, exist_ok=True)
                out_path = os.path.join(args.save_dir, "sample_prediction.jpg")
                cv2.imwrite(out_path, annotated)
                print(f"Saved prediction to {out_path}")
            else:
                # Save in the model's directory
                out_path = os.path.join(os.path.dirname(args.model), "sample_prediction.jpg")
                cv2.imwrite(out_path, annotated)
                print(f"Saved prediction to {out_path}")

    print("\nEvaluation completed.")

if __name__ == "__main__":
    main()