# -*- coding: utf-8 -*-
"""train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IPpYTAg1_qATUZYg40tebxZWbTo5X_BD
"""

#!/usr/bin/env python3
"""
Car Damage Detection with YOLOv8‑seg on CarDD dataset.
Usage:
    python train.py [--data_dir PATH] [--output_dir PATH] [--epochs 50] [--batch 16]
"""

import os
import sys
import argparse
import shutil
import glob
import json
import cv2
import numpy as np
from tqdm import tqdm
from pycocotools import mask as coco_mask
import kagglehub
from ultralytics import YOLO

# ------------------------------
# 1. Parse command line arguments
# ------------------------------
parser = argparse.ArgumentParser(description="Train YOLOv8‑seg on CarDD dataset")
parser.add_argument("--data_dir", type=str, default=None,
                    help="Directory where the CarDD dataset is stored. If not provided, it will be downloaded from Kaggle.")
parser.add_argument("--output_dir", type=str, default="./cardd_training",
                    help="Directory where all training outputs (checkpoints, logs) will be saved.")
parser.add_argument("--epochs", type=int, default=50,
                    help="Total number of training epochs.")
parser.add_argument("--batch", type=int, default=16,
                    help="Batch size (reduce if you run out of GPU memory).")
parser.add_argument("--imgsz", type=int, default=640,
                    help="Input image size for the model.")
parser.add_argument("--model", type=str, default="yolov8n-seg.pt",
                    help="Pretrained model to start from (e.g., yolov8n-seg.pt, yolov8s-seg.pt).")
parser.add_argument("--resume", action="store_true",
                    help="Force resume training from last checkpoint (even if checkpoint not found, it will start fresh).")
parser.add_argument("--no_resume", action="store_true",
                    help="Start fresh training even if a checkpoint exists.")
args = parser.parse_args()

# ------------------------------
# 2. Define class names and their focal‑loss alpha weights
#    (Higher weight for classes that need more attention)
# ------------------------------
CLASS_NAMES = ['dent', 'scratch', 'crack', 'glass shatter', 'tire flat', 'lamp broken']
FOCAL_ALPHA = [1.5, 1.5, 2.5, 1.0, 1.0, 1.0]   # crack gets the highest weight

# ------------------------------
# 3. Helper: Convert COCO annotation to YOLO polygon (for segmentation)
# ------------------------------
def coco_ann_to_yolo_polygon(ann, img_w, img_h):
    """
    Convert a single COCO annotation (with segmentation) into a YOLO‑style line.
    Returns a string: "class_id x1 y1 x2 y2 ... xn yn" (normalized 0‑1)
    """
    seg = ann['segmentation']
    cat_id = ann['category_id'] - 1          # COCO ids start at 1

    if isinstance(seg, dict):                # RLE mask (common in CarDD)
        mask = coco_mask.decode(seg)
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        polygons = []
        for cnt in contours:
            if cnt.shape[0] < 3:
                continue
            cnt = cnt.squeeze().astype(float)
            cnt[:, 0] /= img_w
            cnt[:, 1] /= img_h
            cnt = np.clip(cnt, 0, 1).flatten()
            polygons.append(cnt.tolist())
        if not polygons:
            return None
        polygons.sort(key=len, reverse=True)   # use the largest polygon
        poly = polygons[0]
    else:                                    # already polygon format
        # seg[0] is the first (outer) polygon
        poly = np.array(seg[0]).reshape(-1, 2)
        poly[:, 0] /= img_w
        poly[:, 1] /= img_h
        poly = np.clip(poly, 0, 1).flatten().tolist()

    return f"{cat_id} " + " ".join([f"{x:.6f}" for x in poly])

# ------------------------------
# 4. Convert a whole split (train/val/test) to YOLO format
# ------------------------------
def convert_split(split_name, json_path, img_dir, yolo_root):
    """
    Convert one split (train/val/test) of COCO annotations to YOLO label files.
    Assumes the images have already been copied to yolo_root/<split>/images/.
    """
    print(f"\nProcessing {split_name} split...")
    if not os.path.exists(json_path):
        print(f"ERROR: Annotation file {json_path} not found!")
        return

    with open(json_path, 'r') as f:
        coco_data = json.load(f)

    images = {img['id']: img for img in coco_data['images']}
    annotations = coco_data['annotations']

    # Group annotations by image
    img_to_anns = {}
    for ann in annotations:
        img_to_anns.setdefault(ann['image_id'], []).append(ann)

    print(f"Found {len(img_to_anns)} images with annotations.")

    labels_dir = os.path.join(yolo_root, split_name, 'labels')
    images_dir = os.path.join(yolo_root, split_name, 'images')
    os.makedirs(labels_dir, exist_ok=True)

    for img_id, anns in tqdm(img_to_anns.items(), desc=split_name):
        img_info = images[img_id]
        file_name = img_info['file_name']
        width = img_info['width']
        height = img_info['height']

        # Verify that the image exists (should have been copied earlier)
        img_path = os.path.join(images_dir, file_name)
        if not os.path.exists(img_path):
            print(f"Warning: {img_path} missing, skipping labels for this image.")
            continue

        label_path = os.path.join(labels_dir, os.path.splitext(file_name)[0] + '.txt')
        with open(label_path, 'w') as f:
            for ann in anns:
                if not ann.get('segmentation'):
                    continue
                if ann.get('area', 0) < 100:   # skip very tiny masks (noise)
                    continue
                yolo_line = coco_ann_to_yolo_polygon(ann, width, height)
                if yolo_line:
                    f.write(yolo_line + '\n')
    print(f"Labels created for {split_name}.")

# ------------------------------
# 5. Prepare the dataset: download, copy images, convert annotations
# ------------------------------
def prepare_dataset():
    """
    Downloads the CarDD dataset from Kaggle,
    copies images to the YOLO folder, and converts COCO annotations to YOLO labels.
    Returns the path to the YOLO‑formatted dataset root.
    """
    # Determine the dataset source
    if args.data_dir and os.path.exists(args.data_dir):
        print(f"Using existing dataset at {args.data_dir}")
        base_dir = args.data_dir
        if not os.path.isdir(os.path.join(base_dir, 'CarDD_release')):
            # Maybe the user gave the root of the downloaded CarDD_release folder?
            # Check for CarDD_release inside the given path.
            possible = os.path.join(base_dir, 'CarDD_release')
            if os.path.isdir(possible):
                base_dir = possible
            else:
                print(f"ERROR: Could not find CarDD_release inside {args.data_dir}. Please provide the correct path.")
                sys.exit(1)
    else:
        print("Downloading CarDD dataset from Kaggle...")
        # This will download to a temporary location like /root/.cache/kagglehub/...
        dataset_path = kagglehub.dataset_download("nasimetemadi/car-damage-detection")
        base_dir = os.path.join(dataset_path, 'CarDD_release')
        if not os.path.isdir(base_dir):
            # Try to locate CarDD_release inside the downloaded folder
            possible = glob.glob(os.path.join(dataset_path, "*CarDD_release*"))
            if possible:
                base_dir = possible[0]
            else:
                print("ERROR: Failed to locate CarDD_release after download.")
                sys.exit(1)
        print(f"Dataset downloaded to {base_dir}")

    # Paths to images and annotations (standard CarDD layout)
    annot_dir = os.path.join(base_dir, 'CarDD_COCO', 'annotations')
    image_dirs = {
        'train': os.path.join(base_dir, 'CarDD_COCO', 'train2017'),
        'val':   os.path.join(base_dir, 'CarDD_COCO', 'val2017'),
        'test':  os.path.join(base_dir, 'CarDD_COCO', 'test2017')
    }

    # Verify that required folders exist
    for split, d in image_dirs.items():
        if not os.path.isdir(d):
            print(f"ERROR: Image folder for {split} not found at {d}")
            sys.exit(1)
    if not os.path.isdir(annot_dir):
        print(f"ERROR: Annotation folder not found at {annot_dir}")
        sys.exit(1)

    # Create YOLO folder structure
    yolo_root = os.path.join(args.output_dir, "CarDD_YOLO")
    os.makedirs(yolo_root, exist_ok=True)
    for split in ['train', 'val', 'test']:
        os.makedirs(os.path.join(yolo_root, split, 'images'), exist_ok=True)
        os.makedirs(os.path.join(yolo_root, split, 'labels'), exist_ok=True)

    # Copy images
    print("Copying images to YOLO folder...")
    for split, src_dir in image_dirs.items():
        dst_dir = os.path.join(yolo_root, split, 'images')
        for file in os.listdir(src_dir):
            if file.lower().endswith('.jpg'):
                shutil.copy2(os.path.join(src_dir, file), os.path.join(dst_dir, file))
        print(f"  {split}: done")

    # Convert annotations
    convert_split('train',
                  os.path.join(annot_dir, 'instances_train2017.json'),
                  image_dirs['train'],
                  yolo_root)
    convert_split('val',
                  os.path.join(annot_dir, 'instances_val2017.json'),
                  image_dirs['val'],
                  yolo_root)
    convert_split('test',
                  os.path.join(annot_dir, 'instances_test2017.json'),
                  image_dirs['test'],
                  yolo_root)

    # Create the dataset YAML file
    yaml_path = os.path.join(yolo_root, 'car_damage.yaml')
    with open(yaml_path, 'w') as f:
        f.write(f"""# CarDD dataset for YOLO segmentation
path: {yolo_root}
train: train/images
val: val/images
test: test/images

nc: {len(CLASS_NAMES)}
names: {CLASS_NAMES}
""")
    print(f"YAML file created at {yaml_path}")
    return yaml_path, yolo_root

# ------------------------------
# 6. Main training routine
# ------------------------------
def main():
    # First, prepare the dataset (download, convert, etc.)
    yaml_path, yolo_root = prepare_dataset()

    # Determine where checkpoints should be saved
    run_name = "car_damage_run"
    project_dir = os.path.join(args.output_dir, "runs")
    checkpoint_path = os.path.join(project_dir, run_name, "weights", "last.pt")

    # Decide whether to resume or start fresh
    resume = False
    if os.path.exists(checkpoint_path) and not args.no_resume:
        print(f"✅ Existing checkpoint found at {checkpoint_path}")
        if args.resume:
            resume = True
        else:
            ans = input("Resume training from last checkpoint? (y/n) ")
            resume = ans.lower().startswith('y')
        if resume:
            print("Resuming training...")
            model = YOLO(checkpoint_path)
            # Resume training – YOLO will continue from the last epoch
            model.train(resume=True)
            return
    else:
        print("🆕 No checkpoint found, starting fresh training...")

    # Start fresh training
    print("Starting fresh training...")
    model = YOLO(args.model)

    # Training arguments
    train_kwargs = {
        'data': yaml_path,
        'epochs': args.epochs,
        'imgsz': args.imgsz,
        'batch': args.batch,
        'project': project_dir,
        'name': run_name,
        'exist_ok': True,
        'save_period': 5,               # save checkpoint every 5 epochs
        'patience': 20,                 # early stopping patience
        'focal_loss_gamma': 1.5,        # focal loss gamma
        'focal_loss_alpha': FOCAL_ALPHA,   # class weights (list)
    }

    model.train(**train_kwargs)
    print("Training completed.")

# ------------------------------
# 7. Entry point
# ------------------------------
if __name__ == "__main__":
    main()